"""The browser gate has to be able to fail too, so this runs it against inputs that should.

``tools/a11y_browser`` is the check behind README.md's claim that these pages are held to
WCAG 2.2 SC 1.4.10 Reflow and to the axe rule sets in an engine that does layout.
ADR-0004 says a check is not adopted here until it has been seen to fail on the input it
exists to catch, and ``tests/test_a11y_gate.py`` is the model: the same evidence, for the
jsdom half.

Three of these cases are things the jsdom gate cannot see at all, which is the argument
for having a second engine:

* a page that scrolls sideways at 320 CSS pixels, because reflow is a property of the
  viewport and jsdom has none;
* a scrollable container nobody can focus, because whether a container scrolls depends
  on layout, and this was a real serious-rated defect on the published pages until the
  browser run found it;
* text that fails the contrast threshold, which jsdom reports as undecided.

The last of those is why the browser run declares nothing undecidable. In jsdom four
rules land in ``incomplete`` and are declared in ``tools/a11y.mjs`` with a reason. Here
an undecided rule fails, because there is nothing this engine cannot decide.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
HARNESS = ROOT / "tools" / "a11y_browser"
RUNNER = HARNESS / "node_modules" / ".bin" / "playwright"

CLEAN = 0

# The harness needs node, the packages `make browser-sync` installs, and a browser
# binary. `make verify` runs browser-sync before test for exactly this reason. If the
# toolchain is genuinely absent these tests skip locally and say so, but never on CI,
# where a silently skipped gate test is the same lie the gate itself would be telling.
NODE = shutil.which("node")
BROWSERS = Path.home() / "Library" / "Caches" / "ms-playwright"
LINUX_BROWSERS = Path.home() / ".cache" / "ms-playwright"
HAVE_TOOLCHAIN = (
    NODE is not None
    and RUNNER.is_file()
    and (BROWSERS.is_dir() or LINUX_BROWSERS.is_dir())
)

if not HAVE_TOOLCHAIN and os.environ.get("CI"):  # pragma: no cover - CI-only guard
    raise RuntimeError(
        "node, @playwright/test or the browser binary is missing and CI is set: the "
        "browser WCAG gate's own tests cannot run, and a skipped gate test must not "
        "read as a passing one. Run `make browser-sync` before `make test`."
    )

pytestmark = [
    pytest.mark.skipif(
        not HAVE_TOOLCHAIN,
        reason="node with @playwright/test and a browser is required; run `make browser-sync`",
    ),
    pytest.mark.slow,
]


def run(spec: str, site_dir: Path) -> subprocess.CompletedProcess[str]:
    """Run one spec file against one directory of pages."""
    # Fixed argv, absolute runner, no shell. The only interpolated value is the test's
    # own tmp_path, passed through the environment rather than the command line.
    return subprocess.run(  # noqa: S603
        [str(RUNNER), "test", spec],
        capture_output=True,
        text=True,
        check=False,
        cwd=HARNESS,
        env={**os.environ, "PERIMETER_SITE_DIR": str(site_dir), "CI": ""},
    )


def page(body: str, *, style: str = "") -> str:
    """A minimal conformant page, with the body under test dropped into its main."""
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<title>Browser gate test page</title>"
        f"<style>body{{margin:0;background:#fff;color:#111}}{style}</style></head><body>"
        "<nav aria-label='test'><a href='#content'>Skip to content</a></nav>"
        f"<main id='content'><h1>Browser gate test page</h1>{body}</main>"
        "<footer><p>Test material generated by tests/test_a11y_browser_gate.py.</p>"
        "</footer></body></html>"
    )


def site(tmp_path: Path, body: str, *, style: str = "") -> Path:
    out = tmp_path / "pages"
    out.mkdir()
    (out / "under-test.html").write_text(page(body, style=style), encoding="utf-8")
    return out


CLEAN_BODY = "<p>Ordinary prose that wraps inside any viewport.</p>"


# --- the gate passes what it should ---------------------------------------------------


@pytest.mark.parametrize("spec", ["reflow.spec.ts", "axe.spec.ts"])
def test_a_conformant_page_passes_both_specs(spec: str, tmp_path: Path) -> None:
    """The positive control. Without it a gate that fails everything looks like a gate."""
    result = run(spec, site(tmp_path, CLEAN_BODY))
    assert result.returncode == CLEAN, result.stdout + result.stderr


# --- reflow: SC 1.4.10, which no DOM-only engine can decide ---------------------------


def test_a_page_that_scrolls_sideways_at_320px_fails(tmp_path: Path) -> None:
    body = "<div class='wide'>A block wider than any narrow viewport.</div>"
    result = run(
        "reflow.spec.ts",
        site(tmp_path, body, style=".wide{width:900px;background:#eee}"),
    )
    assert result.returncode != CLEAN
    assert "SC 1.4.10" in result.stdout


def test_text_that_spills_out_of_a_correctly_sized_block_fails(tmp_path: Path) -> None:
    """The sneaky half: the box fits, the content does not, and nothing looks wrong."""
    body = "<p class='long'>https://example.invalid/" + "a" * 300 + "</p>"
    result = run(
        "reflow.spec.ts",
        site(tmp_path, body, style=".long{overflow-x:visible;word-break:normal}"),
    )
    assert result.returncode != CLEAN
    assert "SC 1.4.10" in result.stdout


# --- axe in an engine that does layout ------------------------------------------------


def test_a_scrollable_region_nobody_can_focus_fails(tmp_path: Path) -> None:
    """The defect this harness found on the published pages, kept as a regression.

    A container with overflow-x: auto scrolls for a pointer and not for a keyboard. It
    is invisible to jsdom, which computes no layout and so never knows the container
    scrolls at all.
    """
    body = (
        "<div class='box'><table><caption>Wide</caption><tbody><tr>"
        + "".join(f"<td>cell {n}</td>" for n in range(40))
        + "</tr></tbody></table></div>"
    )
    result = run(
        "axe.spec.ts",
        site(
            tmp_path,
            body,
            style=".box{overflow-x:auto;width:200px}.box td{white-space:nowrap}",
        ),
    )
    assert result.returncode != CLEAN
    assert "scrollable-region-focusable" in result.stdout


def test_text_below_the_contrast_threshold_fails(tmp_path: Path) -> None:
    """jsdom paints nothing and files this as undecided; a browser decides it."""
    body = "<p class='faint'>Grey on white, below 4.5:1.</p>"
    result = run(
        "axe.spec.ts",
        site(tmp_path, body, style=".faint{color:#aaa;background:#fff}"),
    )
    assert result.returncode != CLEAN
    assert "color-contrast" in result.stdout


def test_a_pointer_target_under_24px_fails(tmp_path: Path) -> None:
    """SC 2.5.8. Needs box geometry, which is the whole reason it was unchecked."""
    body = "<p><a class='tiny' href='#content'>a</a> <a class='tiny' href='#content'>b</a></p>"
    result = run(
        "axe.spec.ts",
        site(
            tmp_path,
            body,
            style=".tiny{display:inline-block;width:8px;height:8px;overflow:hidden;font-size:6px}",
        ),
    )
    assert result.returncode != CLEAN
    assert "target-size" in result.stdout


# --- a gate that can find nothing to examine fails ------------------------------------


@pytest.mark.parametrize("spec", ["reflow.spec.ts", "axe.spec.ts"])
def test_a_directory_with_no_pages_fails_rather_than_passing(
    spec: str, tmp_path: Path
) -> None:
    empty = tmp_path / "empty"
    empty.mkdir()
    result = run(spec, empty)
    assert result.returncode != CLEAN
    assert "no .html files" in result.stdout + result.stderr


@pytest.mark.parametrize("spec", ["reflow.spec.ts", "axe.spec.ts"])
def test_a_missing_directory_fails_rather_than_passing(
    spec: str, tmp_path: Path
) -> None:
    result = run(spec, tmp_path / "was-never-built")
    assert result.returncode != CLEAN
    assert "cannot read" in result.stdout + result.stderr
